create table utilisateur(
ID  NUMBER NOT NULL,
NOM_PRENOM  VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
MOT_DE_PASSE VARCHAR2(100) NOT NULL,
TELEPHONE     VARCHAR2(15) NOT NULL
);
create table despbien(
ID_DESP NUMBER NOT NULL ,
type VARCHAR2(10) NOT NULL ,
LOCALISATION  VARCHAR2(10)NOT NULL ,
ADRESS VARCHAR2(20)NOT NULL,
LOUERVENDER VARCHAR2(10) NOT NULL ,
INTERFACE NUMBER(15) NOT NULL 
PRIX  NUMBER(15) NOT NULL ,
NUMEROTELE  NUMBER(10)

);